name: Build & deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - uses: actions/checkout@v3  # Atualizado para v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # Atualizado para v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install   
    - name: Build project
      run: yarn build
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3  # Atualizado para v3
      with:
        name: production-files
        path: ./build
       
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
  
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3  # Atualizado para v3
        with:
          name: production-files
          path: ./build
  
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
