name: Node.js CI

on:
  push:
    branches:
      - main  # Aciona para commits na branch main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Certifique-se de que é a branch correta
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: List files in build directory  # Listar arquivos gerados no build
      run: ls -al ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        target_branch: gh-pages  # Garantir que o deploy vai para gh-pages
